name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge release1 -> develop
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: release1
          target_branch: develop
          github_token: ${{ github.token }}
